trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      #vmImage: $(vmImageName)
      vmImage: "ubuntu-latest"
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        #repository: $(imageRepository)
        repository: "containerRegistryRroart2"
        #dockerfile: $(dockerfilePath)
        dockerfile: "."
        #containerRegistry: $(dockerRegistryServiceConnection)
        #containerRegistry: "dockerRegistryServiceConnection"
        tags: |
          #$(tag)
          "latest"
