apiVersion: v1
kind: Service
metadata:
  name: bankcore
  labels:
    app: bankcore
spec:
  clusterIP: None
  ports:
    - port: 80
      name: bankcore
  selector:
    app: bankcore
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankcore
  labels:
    app: bankcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankcore
  template:
    metadata:
      labels:
        app: bankcore
    spec:
      containers:
      - name: bankcore
        image: bankcore
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bankcore
  labels:
    app: bankcore
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bankcore
  sessionAffinity: None  
status:
  loadBalancer: {}    
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: name-virtual-host-ingress
spec:
  rules:
  - host: core.catwarebank.tk
    http:
      paths:
      - backend:
          serviceName: bankcore
          servicePort: 80
  - host: www.catwarebank.tk
    http:
      paths:
      - backend:
          serviceName: bankweb
          servicePort: 80
